name: maven dependency submission
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Dependencies
    runs-on: ubuntu-latest
    permissions: # The Dependency Submission API requires write permission
      contents: write
    steps:
      - name: Submit Dependency Snapshot
        uses: advanced-security/maven-dependency-submission-action@v3
